### ISSUE TITLE
[bug] an unexpected keyword argument 'favicon_path'

### ISSUE THREAD

**Issue by fengwang** [calibrain/calibre-web-automated-book-downloader#2]
After setting up the docker container using docker-compose.yml file, I continued to download books. The first two books failed to download. I looked at the docker logs, the related information is as follows:

```
2024-12-18 13:04:04,047 - backend - INFO - Starting download loop
2024-12-18 13:04:04,079 - __main__ - INFO - Starting Flask application on 0.0.0.0:8084
 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8084
 * Running on http://172.25.0.2:8084
Press CTRL+C to quit
127.0.0.1 - - [18/Dec/2024 13:04:06] "GET /request/api/status HTTP/1.1" 200 -
➜  calibre_web_downloader docker logs calibre-web-automated-book-downloader 
2024-12-18 13:04:04,047 - backend - INFO - Starting download loop
2024-12-18 13:04:04,079 - __main__ - INFO - Starting Flask application on 0.0.0.0:8084
 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8084
 * Running on http://172.25.0.2:8084
Press CTRL+C to quit
127.0.0.1 - - [18/Dec/2024 13:04:06] "GET /request/api/status HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2024 13:04:36] "GET /request/api/status HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:04:52] "GET / HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:04:52] "GET /request/static/js/main.js HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:04:52] "GET /request/static/css/styles.css HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:04:52] "GET /request/api/status HTTP/1.1" 200 -
[2024-12-18 13:04:52,707] ERROR in app: Exception on /request/static/favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: favicon() got an unexpected keyword argument 'favicon_path'
2024-12-18 13:04:52,710 - __main__ - ERROR - 500 error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
10.147.19.211 - - [18/Dec/2024 13:04:52] "GET /request/static/favicon.ico HTTP/1.1" 500 -
2024-12-18 13:05:00,363 - network - INFO - GET: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&lang=en&sort=&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&lang=en&q=Heidi
10.147.19.211 - - [18/Dec/2024 13:05:03] "GET /request/api/search?query=Heidi HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2024 13:05:07] "GET /request/api/status HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2024 13:05:37] "GET /request/api/status HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:05:52] "GET /request/api/status HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2024 13:06:07] "GET /request/api/status HTTP/1.1" 200 -
2024-12-18 13:06:14,285 - network - INFO - GET: https://annas-archive.org/md5/14b2e97fd747d2cf40cb36819c8b106f
10.147.19.211 - - [18/Dec/2024 13:06:18] "GET /request/api/info?id=14b2e97fd747d2cf40cb36819c8b106f HTTP/1.1" 200 -
2024-12-18 13:06:26,536 - network - INFO - GET: https://annas-archive.org/md5/14b2e97fd747d2cf40cb36819c8b106f
2024-12-18 13:06:27,840 - backend - INFO - Book queued: Miss Delacourt Has Her Day
10.147.19.211 - - [18/Dec/2024 13:06:27] "GET /request/api/download?id=14b2e97fd747d2cf40cb36819c8b106f HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:06:27] "GET /request/api/status HTTP/1.1" 200 -
2024-12-18 13:06:29,054 - network - INFO - GET_CF: https://annas-archive.org/slow_download/14b2e97fd747d2cf40cb36819c8b106f/0/2
127.0.0.1 - - [18/Dec/2024 13:06:37] "GET /request/api/status HTTP/1.1" 200 -
2024-12-18 13:06:43,175 - book_manager - INFO - Downloading Miss Delacourt Has Her Day from https://nrzr.li/d3/y/1734534398/10000/g5/zlib1/pilimi-zlib-5550000-5579999/5579454~/ZuQ7doNirq4ixQawcNqOwQ/Miss%20Delacourt%20Has%20Her%20Day%20--%20Heidi%20Ashworth%20--%202014%20--%2014b2e97fd747d2cf40cb36819c8b106f%20--%20Anna%E2%80%99s%20Archive.mobi
2024-12-18 13:06:43,175 - network - INFO - Downloading from: https://nrzr.li/d3/y/1734534398/10000/g5/zlib1/pilimi-zlib-5550000-5579999/5579454~/ZuQ7doNirq4ixQawcNqOwQ/Miss%20Delacourt%20Has%20Her%20Day%20--%20Heidi%20Ashworth%20--%202014%20--%2014b2e97fd747d2cf40cb36819c8b106f%20--%20Anna%E2%80%99s%20Archive.mobi
10.147.19.211 - - [18/Dec/2024 13:06:46] "GET / HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:06:46] "GET /request/static/css/styles.css HTTP/1.1" 304 -
10.147.19.211 - - [18/Dec/2024 13:06:46] "GET /request/static/js/main.js HTTP/1.1" 304 -
10.147.19.211 - - [18/Dec/2024 13:06:46] "GET /request/api/status HTTP/1.1" 200 -
[2024-12-18 13:06:46,699] ERROR in app: Exception on /request/static/favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: favicon() got an unexpected keyword argument 'favicon_path'
2024-12-18 13:06:46,700 - __main__ - ERROR - 500 error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
10.147.19.211 - - [18/Dec/2024 13:06:46] "GET /request/static/favicon.ico HTTP/1.1" 500 -
127.0.0.1 - - [18/Dec/2024 13:07:07] "GET /request/api/status HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2024 13:07:37] "GET /request/api/status HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:07:43] "GET / HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:07:43] "GET /request/static/css/styles.css HTTP/1.1" 304 -
10.147.19.211 - - [18/Dec/2024 13:07:43] "GET /request/static/js/main.js HTTP/1.1" 304 -
10.147.19.211 - - [18/Dec/2024 13:07:43] "GET /request/api/status HTTP/1.1" 200 -
[2024-12-18 13:07:43,410] ERROR in app: Exception on /request/static/favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: favicon() got an unexpected keyword argument 'favicon_path'
2024-12-18 13:07:43,412 - __main__ - ERROR - 500 error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
10.147.19.211 - - [18/Dec/2024 13:07:43] "GET /request/static/favicon.ico HTTP/1.1" 500 -
10.147.19.211 - - [18/Dec/2024 13:07:45] "GET / HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:07:45] "GET /request/static/css/styles.css HTTP/1.1" 304 -
10.147.19.211 - - [18/Dec/2024 13:07:45] "GET /request/static/js/main.js HTTP/1.1" 304 -
10.147.19.211 - - [18/Dec/2024 13:07:45] "GET /request/api/status HTTP/1.1" 200 -
[2024-12-18 13:07:45,897] ERROR in app: Exception on /request/static/favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: favicon() got an unexpected keyword argument 'favicon_path'
2024-12-18 13:07:45,898 - __main__ - ERROR - 500 error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
10.147.19.211 - - [18/Dec/2024 13:07:45] "GET /request/static/favicon.ico HTTP/1.1" 500 -
2024-12-18 13:08:04,923 - backend - INFO - Book 14b2e97fd747d2cf40cb36819c8b106f download failed
127.0.0.1 - - [18/Dec/2024 13:08:07] "GET /request/api/status HTTP/1.1" 200 -
2024-12-18 13:08:27,722 - network - INFO - GET: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&lang=en&sort=&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&lang=en&q=WIND%20AND%20TRUTH
10.147.19.211 - - [18/Dec/2024 13:08:31] "GET /request/api/search?query=WIND%20AND%20TRUTH HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2024 13:08:37] "GET /request/api/status HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:08:45] "GET /request/api/status HTTP/1.1" 200 -
➜  calibre_web_downloader docker logs calibre-web-automated-book-downloader 
2024-12-18 13:04:04,047 - backend - INFO - Starting download loop
2024-12-18 13:04:04,079 - __main__ - INFO - Starting Flask application on 0.0.0.0:8084
 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8084
 * Running on http://172.25.0.2:8084
Press CTRL+C to quit
127.0.0.1 - - [18/Dec/2024 13:04:06] "GET /request/api/status HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2024 13:04:36] "GET /request/api/status HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:04:52] "GET / HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:04:52] "GET /request/static/js/main.js HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:04:52] "GET /request/static/css/styles.css HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:04:52] "GET /request/api/status HTTP/1.1" 200 -
[2024-12-18 13:04:52,707] ERROR in app: Exception on /request/static/favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: favicon() got an unexpected keyword argument 'favicon_path'
2024-12-18 13:04:52,710 - __main__ - ERROR - 500 error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
10.147.19.211 - - [18/Dec/2024 13:04:52] "GET /request/static/favicon.ico HTTP/1.1" 500 -
2024-12-18 13:05:00,363 - network - INFO - GET: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&lang=en&sort=&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&lang=en&q=Heidi
10.147.19.211 - - [18/Dec/2024 13:05:03] "GET /request/api/search?query=Heidi HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2024 13:05:07] "GET /request/api/status HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2024 13:05:37] "GET /request/api/status HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:05:52] "GET /request/api/status HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2024 13:06:07] "GET /request/api/status HTTP/1.1" 200 -
2024-12-18 13:06:14,285 - network - INFO - GET: https://annas-archive.org/md5/14b2e97fd747d2cf40cb36819c8b106f
10.147.19.211 - - [18/Dec/2024 13:06:18] "GET /request/api/info?id=14b2e97fd747d2cf40cb36819c8b106f HTTP/1.1" 200 -
2024-12-18 13:06:26,536 - network - INFO - GET: https://annas-archive.org/md5/14b2e97fd747d2cf40cb36819c8b106f
2024-12-18 13:06:27,840 - backend - INFO - Book queued: Miss Delacourt Has Her Day
10.147.19.211 - - [18/Dec/2024 13:06:27] "GET /request/api/download?id=14b2e97fd747d2cf40cb36819c8b106f HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:06:27] "GET /request/api/status HTTP/1.1" 200 -
2024-12-18 13:06:29,054 - network - INFO - GET_CF: https://annas-archive.org/slow_download/14b2e97fd747d2cf40cb36819c8b106f/0/2
127.0.0.1 - - [18/Dec/2024 13:06:37] "GET /request/api/status HTTP/1.1" 200 -
2024-12-18 13:06:43,175 - book_manager - INFO - Downloading Miss Delacourt Has Her Day from https://nrzr.li/d3/y/1734534398/10000/g5/zlib1/pilimi-zlib-5550000-5579999/5579454~/ZuQ7doNirq4ixQawcNqOwQ/Miss%20Delacourt%20Has%20Her%20Day%20--%20Heidi%20Ashworth%20--%202014%20--%2014b2e97fd747d2cf40cb36819c8b106f%20--%20Anna%E2%80%99s%20Archive.mobi
2024-12-18 13:06:43,175 - network - INFO - Downloading from: https://nrzr.li/d3/y/1734534398/10000/g5/zlib1/pilimi-zlib-5550000-5579999/5579454~/ZuQ7doNirq4ixQawcNqOwQ/Miss%20Delacourt%20Has%20Her%20Day%20--%20Heidi%20Ashworth%20--%202014%20--%2014b2e97fd747d2cf40cb36819c8b106f%20--%20Anna%E2%80%99s%20Archive.mobi
10.147.19.211 - - [18/Dec/2024 13:06:46] "GET / HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:06:46] "GET /request/static/css/styles.css HTTP/1.1" 304 -
10.147.19.211 - - [18/Dec/2024 13:06:46] "GET /request/static/js/main.js HTTP/1.1" 304 -
10.147.19.211 - - [18/Dec/2024 13:06:46] "GET /request/api/status HTTP/1.1" 200 -
[2024-12-18 13:06:46,699] ERROR in app: Exception on /request/static/favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: favicon() got an unexpected keyword argument 'favicon_path'
2024-12-18 13:06:46,700 - __main__ - ERROR - 500 error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
10.147.19.211 - - [18/Dec/2024 13:06:46] "GET /request/static/favicon.ico HTTP/1.1" 500 -
127.0.0.1 - - [18/Dec/2024 13:07:07] "GET /request/api/status HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2024 13:07:37] "GET /request/api/status HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:07:43] "GET / HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:07:43] "GET /request/static/css/styles.css HTTP/1.1" 304 -
10.147.19.211 - - [18/Dec/2024 13:07:43] "GET /request/static/js/main.js HTTP/1.1" 304 -
10.147.19.211 - - [18/Dec/2024 13:07:43] "GET /request/api/status HTTP/1.1" 200 -
[2024-12-18 13:07:43,410] ERROR in app: Exception on /request/static/favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: favicon() got an unexpected keyword argument 'favicon_path'
2024-12-18 13:07:43,412 - __main__ - ERROR - 500 error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
10.147.19.211 - - [18/Dec/2024 13:07:43] "GET /request/static/favicon.ico HTTP/1.1" 500 -
10.147.19.211 - - [18/Dec/2024 13:07:45] "GET / HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:07:45] "GET /request/static/css/styles.css HTTP/1.1" 304 -
10.147.19.211 - - [18/Dec/2024 13:07:45] "GET /request/static/js/main.js HTTP/1.1" 304 -
10.147.19.211 - - [18/Dec/2024 13:07:45] "GET /request/api/status HTTP/1.1" 200 -
[2024-12-18 13:07:45,897] ERROR in app: Exception on /request/static/favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: favicon() got an unexpected keyword argument 'favicon_path'
2024-12-18 13:07:45,898 - __main__ - ERROR - 500 error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
10.147.19.211 - - [18/Dec/2024 13:07:45] "GET /request/static/favicon.ico HTTP/1.1" 500 -
2024-12-18 13:08:04,923 - backend - INFO - Book 14b2e97fd747d2cf40cb36819c8b106f download failed
127.0.0.1 - - [18/Dec/2024 13:08:07] "GET /request/api/status HTTP/1.1" 200 -
2024-12-18 13:08:27,722 - network - INFO - GET: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&lang=en&sort=&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&lang=en&q=WIND%20AND%20TRUTH
10.147.19.211 - - [18/Dec/2024 13:08:31] "GET /request/api/search?query=WIND%20AND%20TRUTH HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2024 13:08:37] "GET /request/api/status HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:08:45] "GET /request/api/status HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2024 13:09:07] "GET /request/api/status HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2024 13:09:38] "GET /request/api/status HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:09:46] "GET /request/api/status HTTP/1.1" 200 -
2024-12-18 13:09:51,330 - network - INFO - GET: https://annas-archive.org/md5/52a9200d486b0857b006bf39206e22d2
2024-12-18 13:09:53,630 - backend - INFO - Book queued: An Ugly Truth: Inside Facebook's Battle for Domination
10.147.19.211 - - [18/Dec/2024 13:09:53] "GET /request/api/download?id=52a9200d486b0857b006bf39206e22d2 HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:09:53] "GET /request/api/status HTTP/1.1" 200 -
2024-12-18 13:09:54,928 - network - INFO - GET_CF: https://annas-archive.org/slow_download/52a9200d486b0857b006bf39206e22d2/0/2
2024-12-18 13:10:01,299 - book_manager - INFO - Downloading An Ugly Truth: Inside Facebook's Battle for Domination from https://nrzr.li/d3/y/1734534596/10000/g4/libgenrs_nonfiction/4132000/52a9200d486b0857b006bf39206e22d2~/q5llQkLY0epomGn6K_pXIw/An%20Ugly%20Truth%3A%20Inside%20Facebook%27s%20Battle%20for%20Domination%20--%20Sheera%20Frenkel%3B%20Cecilia%20Kang%20--%202021%20--%20HARPERCOLLINS%20--%209780062960672%20--%2052a9200d486b0857b006bf39206e22d2%20--%20Anna%E2%80%99s%20Archive.epub
2024-12-18 13:10:01,299 - network - INFO - Downloading from: https://nrzr.li/d3/y/1734534596/10000/g4/libgenrs_nonfiction/4132000/52a9200d486b0857b006bf39206e22d2~/q5llQkLY0epomGn6K_pXIw/An%20Ugly%20Truth%3A%20Inside%20Facebook%27s%20Battle%20for%20Domination%20--%20Sheera%20Frenkel%3B%20Cecilia%20Kang%20--%202021%20--%20HARPERCOLLINS%20--%209780062960672%20--%2052a9200d486b0857b006bf39206e22d2%20--%20Anna%E2%80%99s%20Archive.epub
127.0.0.1 - - [18/Dec/2024 13:10:08] "GET /request/api/status HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2024 13:10:38] "GET /request/api/status HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:10:46] "GET /request/api/status HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2024 13:11:08] "GET /request/api/status HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:11:23] "GET / HTTP/1.1" 200 -
10.147.19.211 - - [18/Dec/2024 13:11:23] "GET /request/static/js/main.js HTTP/1.1" 304 -
10.147.19.211 - - [18/Dec/2024 13:11:23] "GET /request/static/css/styles.css HTTP/1.1" 304 -
10.147.19.211 - - [18/Dec/2024 13:11:23] "GET /request/api/status HTTP/1.1" 200 -
[2024-12-18 13:11:24,105] ERROR in app: Exception on /request/static/favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: favicon() got an unexpected keyword argument 'favicon_path'
2024-12-18 13:11:24,106 - __main__ - ERROR - 500 error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
10.147.19.211 - - [18/Dec/2024 13:11:24] "GET /request/static/favicon.ico HTTP/1.1" 500 -
```

**Comment by calibrain** [comment]
Hi, sorry this happened
The favicon issue is a red herring,  its just unable to find the favicon to display on the browser title. (but thank you for the report, I fixed it and deployed an updated version)

I just tried for the book "An Ugly Truth: Inside Facebook's Battle for Domination", and it seems to be working fine
Note that it does take some time to download books, from a few minutes up to 15 minutes (in some cases there are wait times and throttling applied)
Did the "Download Status" say "error" ?
If it says "queued" or "downloading", give it some time, it should auto refresh
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/9694993e-af9b-4ad0-b5da-1b9884f8ee50" />
